### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by forstjiri** [rasteron/PyLime#1]
Traceback (most recent call last):
  File "/home/jirka/Plocha/PyLime-master/pylime.py", line 33, in <module>
    root.tk.call('wm', 'iconbitmap', root, '-default', 'icon.ico')
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"

As i understand you need to use xbm on Linux 
http://stackoverflow.com/questions/5351703/help-with-changing-icon-of-tk-window

**Comment by rasteron** [comment]
Thanks @aiphee I have not fully tested this yet on Linux, but will apply those changes soon.

great stuff with the reference you provided, cheers.

**Comment by rasteron** [comment]
This is now fixed, just used gif instead of xbm which is only black and white. Tested using xubuntu..

![icon](https://cloud.githubusercontent.com/assets/3676827/6064626/2e5c9d72-ad9a-11e4-8696-258b1441e138.jpg)
